export const SITE = {
  website: "https://blog.728370.xyz/",
  author: "Pace",
  profile: "https://github.com/PaceCN",
  desc: "比朋友圈更长一点，比学术论文更有趣一点。",
  title: "Pace的博客",
  ogImage: "favicon.svg",
  lightAndDarkMode: true,
  postPerIndex: 6,
  postPerPage: 12,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: false,
  showBackButton: true,
  homeSidebar: {
    profile: true,
    visits: true,
    tags: true,
    categories: true,
    stack: true,
  },
  editPost: {
    enabled: false,
    text: "在 GitHub 编辑",
    url: "",
  },
  dynamicOgImage: false,
  dir: "ltr",
  lang: "zh-CN",
  timezone: "Asia/Shanghai",
} as const;
