export const SITE = {
  website: "https://astro-paper-18u.pages.dev/",
  author: "wx",
  profile: "https://github.com/PaceCN",
  desc: "Pace Notes 是一个个人技术博客，记录 AI 工具、自动化、Cloudflare、VPS 和独立博客搭建中的真实尝试。",
  title: "Pace Notes",
  ogImage: "favicon.svg",
  lightAndDarkMode: true,
  postPerIndex: 6,
  postPerPage: 12,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: false,
  showBackButton: true,
  homeSidebar: {
    profile: true,
    visits: true,
    tags: true,
    categories: true,
    stack: true,
  },
  editPost: {
    enabled: false,
    text: "在 GitHub 编辑",
    url: "",
  },
  dynamicOgImage: false,
  dir: "ltr",
  lang: "zh-CN",
  timezone: "Asia/Shanghai",
} as const;
